Ogre Procedural: Procedural::Extruder Class Reference
Procedural::Extruder Class Reference
Extrudes a 2D shape along a path to build an extruded mesh.
#include <ProceduralExtruder.h>
Public Types
typedef std::map< unsigned int, const Track * > TrackMap
Public Member Functions
Extruder ()
Default constructor.
void addToTriangleBuffer (TriangleBuffer &buffer) const
Builds the mesh into the given TriangleBuffer.
Extruder & setShapeToExtrude (const Shape *shapeToExtrude)
Sets the shape to extrude.
Extruder & setMultiShapeToExtrude (const MultiShape *multiShapeToExtrude)
Sets the multishape to extrude.
Extruder & setExtrusionPath (const Path *extrusionPath)
Sets the extrusion path.
Extruder & setExtrusionPath (const MultiPath *multiExtrusionPath)
Sets the extrusion multipath.
Extruder & setRotationTrack (const Track *rotationTrack, unsigned int index=0)
Sets the rotation track (optional)
Extruder & setScaleTrack (const Track *scaleTrack, unsigned int index=0)
Sets the scale track (optional)
Extruder & setShapeTextureTrack (const Track *shapeTextureTrack, unsigned int index=0)
Sets the track that maps shape points to V texture coords (optional).
Extruder & setPathTextureTrack (const Track *pathTextureTrack, unsigned int index=0)
Sets the track that maps path points to V texture coord (optional).
Extruder & setCapped (bool capped)
Sets whether caps are added to the extremities or not (not closed paths only)
Ogre::MeshPtr realizeMesh (const std::string &name="", const Ogre::String &group="General")
Builds a mesh.
TriangleBuffer buildTriangleBuffer () const
Outputs a triangleBuffer.
Extruder & setUTile (Ogre::Real uTile)
Sets U Tile, ie the number by which u texture coordinates are multiplied (default=1)
Extruder & setVTile (Ogre::Real vTile)
Sets V Tile, ie the number by which v texture coordinates are multiplied (default=1)
Extruder & setTextureRectangle (const Ogre::RealRect &textureRectangle)
Sets the texture rectangle.
Extruder & setEnableNormals (bool enableNormals)
Sets whether normals are enabled or not (default=true)
Extruder & setNumTexCoordSet (unsigned char numTexCoordSet)
Sets the number of texture coordintate sets (default=1)
Extruder & setSwitchUV (bool switchUV)
Sets whether to switch U and V texture coordinates.
Extruder & setOrientation (const Ogre::Quaternion &orientation)
Sets an orientation to give when building the mesh.
Extruder & setPosition (const Ogre::Vector3 &position)
Sets a translation baked into the resulting mesh.
Extruder & setPosition (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Sets a translation baked into the resulting mesh.
Extruder & setScale (const Ogre::Vector3 &scale)
Sets a scale baked into the resulting mesh.
Extruder & setScale (Ogre::Real scale)
Sets a uniform scale baked into the resulting mesh.
Extruder & setScale (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Sets a scale baked into the resulting mesh.
Extruder & resetTransforms ()
Resets all transforms (orientation, position and scale) that would have been applied to the mesh to their default values.
Protected Member Functions
void addPoint (TriangleBuffer &buffer, const Ogre::Vector3 &position, const Ogre::Vector3 &normal, const Ogre::Vector2 &uv) const
Adds a new point to a triangle buffer, using the format defined for that MeshGenerator.
Protected Attributes
Ogre::Real mUTile
A pointer to the default scene manager.
Ogre::Real mVTile
V tile for texture coords generation.
bool mEnableNormals
Whether to produces normals or not.
unsigned char mNumTexCoordSet
The number of texture coordinate sets to include.
Ogre::Vector2 mUVOrigin
Rectangle in which the texture coordinates will be placed.
bool mSwitchUV
If set to true, the UV coordinates coming from the mesh generator will be switched.
Ogre::Quaternion mOrientation
Orientation to apply the mesh.
Ogre::Vector3 mScale
Scale to apply the mesh.
Ogre::Vector3 mPosition
Position to apply to the mesh.
bool mTransform
Detailed Description
Extrudes a 2D shape along a path to build an extruded mesh.
Can be used to build things such as pipelines, roads...
Generic extrusion
Extrusion with rotation track
Extrusion with scale track
Extrusion with texture track
Multishape extrusion
Note
Concerning UV texCoords, U is along the path and V along the shape.
Member Typedef Documentation
TrackMap
typedef std::map<unsigned int, const Track*> Procedural::Extruder::TrackMap
Constructor & Destructor Documentation
Extruder()
Procedural::Extruder::Extruder ()
Default constructor.
Member Function Documentation
addPoint()
void Procedural::MeshGenerator< Extruder >::addPoint (TriangleBuffer & buffer, const Ogre::Vector3 & position, const Ogre::Vector3 & normal, const Ogre::Vector2 & uv) const protected inherited
Adds a new point to a triangle buffer, using the format defined for that MeshGenerator.
Parameters
buffer the triangle buffer to update
position the position of the new point
normal the normal of the new point
uv the uv texcoord of the new point
addToTriangleBuffer()
void Procedural::Extruder::addToTriangleBuffer (TriangleBuffer & buffer) const virtual
Builds the mesh into the given TriangleBuffer.
Parameters
buffer The TriangleBuffer on where to append the mesh.
Exceptions
Ogre::InvalidStateException Either shape or multishape must be defined!
Ogre::InvalidStateException Required parameter is zero!
Implements Procedural::MeshGenerator< Extruder >.
buildTriangleBuffer()
TriangleBuffer Procedural::MeshGenerator< Extruder >::buildTriangleBuffer inherited
Outputs a triangleBuffer.
realizeMesh()
Ogre::MeshPtr Procedural::MeshGenerator< Extruder >::realizeMesh (const std::string & name = "", const Ogre::String & group = "General") inherited
Builds a mesh.
Parameters
name of the mesh for the MeshManager
group ressource group in which the mesh will be created
resetTransforms()
Extruder & Procedural::MeshGenerator< Extruder >::resetTransforms inherited
Resets all transforms (orientation, position and scale) that would have been applied to the mesh to their default values.
setCapped()
Extruder& Procedural::Extruder::setCapped (bool capped)
Sets whether caps are added to the extremities or not (not closed paths only)
setEnableNormals()
Extruder & Procedural::MeshGenerator< Extruder >::setEnableNormals (bool enableNormals) inherited
Sets whether normals are enabled or not (default=true)
setExtrusionPath() [1/2]
Extruder& Procedural::Extruder::setExtrusionPath (const MultiPath * multiExtrusionPath)
Sets the extrusion multipath.
References Procedural::MultiPath::_calcIntersections(), Procedural::MultiPath::addMultiPath(), and Procedural::MultiPath::clear().
setExtrusionPath() [2/2]
Extruder& Procedural::Extruder::setExtrusionPath (const Path * extrusionPath)
Sets the extrusion path.
References Procedural::MultiPath::_calcIntersections(), Procedural::MultiPath::addPath(), and Procedural::MultiPath::clear().
setMultiShapeToExtrude()
Extruder& Procedural::Extruder::setMultiShapeToExtrude (const MultiShape * multiShapeToExtrude)
Sets the multishape to extrude.
Mutually exclusive with setShapeToExtrude.
References Procedural::MultiShape::addMultiShape(), and Procedural::MultiShape::clear().
setNumTexCoordSet()
Extruder & Procedural::MeshGenerator< Extruder >::setNumTexCoordSet (unsigned char numTexCoordSet) inherited
Sets the number of texture coordintate sets (default=1)
setOrientation()
Extruder & Procedural::MeshGenerator< Extruder >::setOrientation (const Ogre::Quaternion & orientation) inherited
Sets an orientation to give when building the mesh.
setPathTextureTrack()
Extruder& Procedural::Extruder::setPathTextureTrack (const Track * pathTextureTrack, unsigned int index = 0)
Sets the track that maps path points to V texture coord (optional).
setPosition() [1/2]
Extruder & Procedural::MeshGenerator< Extruder >::setPosition (const Ogre::Vector3 & position) inherited
Sets a translation baked into the resulting mesh.
setPosition() [2/2]
Extruder & Procedural::MeshGenerator< Extruder >::setPosition (Ogre::Real x, Ogre::Real y, Ogre::Real z) inherited
Sets a translation baked into the resulting mesh.
setRotationTrack()
Extruder& Procedural::Extruder::setRotationTrack (const Track * rotationTrack, unsigned int index = 0)
Sets the rotation track (optional)
setScale() [1/3]
Extruder & Procedural::MeshGenerator< Extruder >::setScale (const Ogre::Vector3 & scale) inherited
Sets a scale baked into the resulting mesh.
setScale() [2/3]
Extruder & Procedural::MeshGenerator< Extruder >::setScale (Ogre::Real scale) inherited
Sets a uniform scale baked into the resulting mesh.
setScale() [3/3]
Extruder & Procedural::MeshGenerator< Extruder >::setScale (Ogre::Real x, Ogre::Real y, Ogre::Real z) inherited
Sets a scale baked into the resulting mesh.
setScaleTrack()
Extruder& Procedural::Extruder::setScaleTrack (const Track * scaleTrack, unsigned int index = 0)
Sets the scale track (optional)
setShapeTextureTrack()
Extruder& Procedural::Extruder::setShapeTextureTrack (const Track * shapeTextureTrack, unsigned int index = 0)
Sets the track that maps shape points to V texture coords (optional).
Warning : if used with multishape, all shapes will have the same track.
setShapeToExtrude()
Extruder& Procedural::Extruder::setShapeToExtrude (const Shape * shapeToExtrude)
Sets the shape to extrude.
Mutually exclusive with setMultiShapeToExtrude.
References Procedural::MultiShape::addShape(), and Procedural::MultiShape::clear().
setSwitchUV()
Extruder & Procedural::MeshGenerator< Extruder >::setSwitchUV (bool switchUV) inherited
Sets whether to switch U and V texture coordinates.
setTextureRectangle()
Extruder & Procedural::MeshGenerator< Extruder >::setTextureRectangle (const Ogre::RealRect & textureRectangle) inherited
Sets the texture rectangle.
setUTile()
Extruder & Procedural::MeshGenerator< Extruder >::setUTile (Ogre::Real uTile) inherited
Sets U Tile, ie the number by which u texture coordinates are multiplied (default=1)
setVTile()
Extruder & Procedural::MeshGenerator< Extruder >::setVTile (Ogre::Real vTile) inherited
Sets V Tile, ie the number by which v texture coordinates are multiplied (default=1)
Member Data Documentation
mEnableNormals
bool Procedural::MeshGenerator< Extruder >::mEnableNormals protected inherited
Whether to produces normals or not.
mNumTexCoordSet
unsigned char Procedural::MeshGenerator< Extruder >::mNumTexCoordSet protected inherited
The number of texture coordinate sets to include.
mOrientation
Ogre::Quaternion Procedural::MeshGenerator< Extruder >::mOrientation protected inherited
Orientation to apply the mesh.
mPosition
Ogre::Vector3 Procedural::MeshGenerator< Extruder >::mPosition protected inherited
Position to apply to the mesh.
mScale
Ogre::Vector3 Procedural::MeshGenerator< Extruder >::mScale protected inherited
Scale to apply the mesh.
mSwitchUV
bool Procedural::MeshGenerator< Extruder >::mSwitchUV protected inherited
If set to true, the UV coordinates coming from the mesh generator will be switched.
It can be used, for example, if your texture doesn't fit the mesh generator's assumptions about UV. If UV were to fit in a given rectangle, they still fit in it after the switch.
mTransform
bool Procedural::MeshGenerator< Extruder >::mTransform protected inherited
mUTile
Ogre::Real Procedural::MeshGenerator< Extruder >::mUTile protected inherited
A pointer to the default scene manager.
U tile for texture coords generation
mUVOrigin
Ogre::Vector2 Procedural::MeshGenerator< Extruder >::mUVOrigin protected inherited
Rectangle in which the texture coordinates will be placed.
mVTile
Ogre::Real Procedural::MeshGenerator< Extruder >::mVTile protected inherited
V tile for texture coords generation.
The documentation for this class was generated from the following file:
ProceduralExtruder.h