Ogre Procedural: Procedural::TriangleShape Class Reference
Procedural::TriangleShape Class Reference
Shape
Builds a triangele shape.
#include <ProceduralShapeGenerators.h>
Public Member Functions
TriangleShape ()
Default constructor.
TriangleShape & setLength (Ogre::Real length)
Creates an equilateral triangle.
TriangleShape & setLengthA (Ogre::Real length)
Sets length of edge A.
TriangleShape & setLengthB (Ogre::Real length)
Sets length of edge B.
TriangleShape & setLengthC (Ogre::Real length)
Sets length of edge C.
Shape realizeShape ()
Builds the shape.
Detailed Description
Builds a triangele shape.
Constructor & Destructor Documentation
TriangleShape()
Procedural::TriangleShape::TriangleShape ()
Default constructor.
Member Function Documentation
realizeShape()
Shape Procedural::TriangleShape::realizeShape ()
Builds the shape.
References Ogre::Math::ACos(), Procedural::Shape::addPoint(), Procedural::Shape::close(), Ogre::Math::Cos(), Ogre::Math::Sin(), and Procedural::Shape::translate().
setLength()
TriangleShape& Procedural::TriangleShape::setLength (Ogre::Real length)
Creates an equilateral triangle.
Exceptions
Ogre::InvalidStateException Length of triangle edges must be longer than 0!
References Ogre::Exception::ERR_INVALID_STATE, and OGRE_EXCEPT.
setLengthA()
TriangleShape& Procedural::TriangleShape::setLengthA (Ogre::Real length)
Sets length of edge A.
Exceptions
Ogre::InvalidStateException Length of triangle edge must be longer than 0!
Ogre::InvalidStateException Length of triangle edge A must be shorter or equal than B+C!
References Ogre::Exception::ERR_INVALID_STATE, and OGRE_EXCEPT.
setLengthB()
TriangleShape& Procedural::TriangleShape::setLengthB (Ogre::Real length)
Sets length of edge B.
Exceptions
Ogre::InvalidStateException Length of triangle edge must be longer than 0!
Ogre::InvalidStateException Length of triangle edge A must be shorter or equal than B+C!
References Ogre::Exception::ERR_INVALID_STATE, and OGRE_EXCEPT.
setLengthC()
TriangleShape& Procedural::TriangleShape::setLengthC (Ogre::Real length)
Sets length of edge C.
Exceptions
Ogre::InvalidStateException Length of triangle edge must be longer than 0!
Ogre::InvalidStateException Length of triangle edge A must be shorter or equal than B+C!
References Ogre::Exception::ERR_INVALID_STATE, and OGRE_EXCEPT.
The documentation for this class was generated from the following file:
ProceduralShapeGenerators.h