Ogre Procedural: Procedural::Shape Class Reference
Procedural::Shape Class Reference
Shape
#include <ProceduralShape.h>
Public Member Functions
Shape ()
Default constructor.
Shape & addPoint (const Ogre::Vector2 &pt)
Adds a point to the shape.
Shape & addPoint (Ogre::Real x, Ogre::Real y)
Adds a point to the shape.
Shape & insertPoint (size_t index, Ogre::Real x, Ogre::Real y)
Inserts a point to the shape.
Shape & insertPoint (size_t index, const Ogre::Vector2 &pt)
Inserts a point to the shape.
Shape & addPointRel (const Ogre::Vector2 &pt)
Adds a point to the shape, relative to the last point added.
Shape & addPointRel (Ogre::Real x, Ogre::Real y)
Adds a point to the shape, relative to the last point added.
Shape & appendShape (const Shape &other)
Appends another shape at the end of this one.
Shape & appendShapeRel (const Shape &other)
Appends another shape at the end of this one, relative to the last point of this shape.
Shape extractSubShape (unsigned int first, unsigned int last)
Extracts a part of the shape as a new shape.
Shape & reverse ()
Reverses direction of the shape The outside is preserved.
Shape & reset ()
Clears the content of the shape.
Path convertToPath () const
Converts the shape to a path, with Y=0.
Track convertToTrack (Track::AddressingMode addressingMode=Track::AM_RELATIVE_LINEIC) const
Outputs a track, with Key=X and Value=Y.
std::vector< Ogre::Vector2 > getPoints () const
Gets a copy of raw vector data of this shape.
std::vector< Ogre::Vector2 > & getPointsReference ()
Gets raw vector data of this shape as a non-const reference.
const std::vector< Ogre::Vector2 > & getPointsReference () const
Gets raw vector data of this shape as a non-const reference.
const Ogre::Vector2 & getPoint (int i) const
Bounds-safe method to get a point : it will allow you to go beyond the bounds.
unsigned int getBoundedIndex (int i) const
const std::vector< Ogre::Vector2 >::size_type getPointCount () const
Gets number of points in current point list.
Shape & close ()
Makes the shape a closed shape, ie it will automatically connect the last point to the first point.
Shape & setOutSide (Side side)
Sets which side (left or right) is on the outside of the shape.
Side getOutSide () const
Gets which side is out.
Shape & switchSide ()
Switches the inside and the outside.
size_t getSegCount () const
Gets the number of segments in that shape.
bool isClosed () const
Gets whether the shape is closed or not.
Ogre::Vector2 getDirectionAfter (unsigned int i) const
Returns local direction after the current point.
Ogre::Vector2 getDirectionBefore (unsigned int i) const
Returns local direction after the current point.
Ogre::Vector2 getAvgDirection (unsigned int i) const
Gets the average between before direction and after direction.
Ogre::Vector2 getNormalAfter (unsigned int i) const
Gets the shape normal just after that point.
Ogre::Vector2 getNormalBefore (unsigned int i) const
Gets the shape normal just before that point.
Ogre::Vector2 getAvgNormal (unsigned int i) const
Gets the "normal" of that point ie an average between before and after normals.
Ogre::MeshPtr realizeMesh (const std::string &name="") const
Outputs a mesh representing the shape.
void _appendToManualObject (Ogre::ManualObject *manual) const
Appends the shape vertices to a manual object being edited.
bool isPointInside (const Ogre::Vector2 &point) const
Tells whether a point is inside a shape or not.
MultiShape booleanIntersect (const Shape &other) const
Computes the intersection between this shape and another one.
MultiShape booleanUnion (const Shape &other) const
Computes the union between this shape and another one.
MultiShape booleanDifference (const Shape &other) const
Computes the difference between this shape and another one.
Side findRealOutSide () const
On a closed shape, find if the outside is located on the right or on the left.
bool isOutsideRealOutside () const
Determines whether the outside as defined by user equals "real" outside.
Shape mergeKeysWithTrack (const Track &track) const
Creates a shape with the keys of this shape and extra keys coming from a track.
Shape & translate (const Ogre::Vector2 &translation)
Applies the given translation to all the points already defined.
Shape & translate (Ogre::Real translationX, Ogre::Real translationY)
Applies the given translation to all the points already defined.
Shape & rotate (Ogre::Radian angle)
Applies the given rotation to all the points already defined.
Shape & scale (Ogre::Real amount)
Applies the given scale to all the points already defined.
Shape & scale (Ogre::Real scaleX, Ogre::Real scaleY)
Applies the given scale to all the points already defined.
Shape & scale (const Ogre::Vector2 &amount)
Applies the given scale to all the points already defined.
Shape & reflect (const Ogre::Vector2 &normal)
Reflect all points in this shape against a zero-origined line with a given normal.
Shape & mirror (bool flip=false)
Create a symetric copy at the origin point.
Shape & mirror (Ogre::Real x, Ogre::Real y, bool flip=false)
Create a symetric copy at a given point.
Shape & mirrorAroundPoint (Ogre::Vector2 point, bool flip=false)
Create a symetric copy at a given point.
Shape & mirrorAroundAxis (const Ogre::Vector2 &axis, bool flip=false)
Create a symetric copy at a given axis.
Ogre::Real getTotalLength () const
Returns the total lineic length of that shape.
Ogre::Vector2 getPosition (unsigned int i, Ogre::Real coord) const
Gets a position on the shape with index of the point and a percentage of position on the segment.
Ogre::Vector2 getPosition (Ogre::Real coord) const
Gets a position on the shape from lineic coordinate.
Ogre::Real findBoundingRadius () const
Computes the radius of a bounding circle centered on the origin.
MultiShape thicken (Ogre::Real amount)
Applies a "thickness" to a shape, ie a bit like the extruder, but in 2D.
Detailed Description
Describes a succession of interconnected 2D points. It can be closed or not, and there's always an outside and an inside
Constructor & Destructor Documentation
Shape()
Procedural::Shape::Shape ()
Default constructor.
Member Function Documentation
_appendToManualObject()
void Procedural::Shape::_appendToManualObject (Ogre::ManualObject * manual) const
Appends the shape vertices to a manual object being edited.
addPoint() [1/2]
Shape& Procedural::Shape::addPoint (const Ogre::Vector2 & pt)
Adds a point to the shape.
Referenced by extractSubShape(), Procedural::RectangleShape::realizeShape(), Procedural::CircleShape::realizeShape(), Procedural::EllipseShape::realizeShape(), and Procedural::TriangleShape::realizeShape().
addPoint() [2/2]
Shape& Procedural::Shape::addPoint (Ogre::Real x, Ogre::Real y)
Adds a point to the shape.
addPointRel() [1/2]
Shape& Procedural::Shape::addPointRel (const Ogre::Vector2 & pt)
Adds a point to the shape, relative to the last point added.
addPointRel() [2/2]
Shape& Procedural::Shape::addPointRel (Ogre::Real x, Ogre::Real y)
Adds a point to the shape, relative to the last point added.
appendShape()
Shape& Procedural::Shape::appendShape (const Shape & other)
Appends another shape at the end of this one.
appendShapeRel()
Shape& Procedural::Shape::appendShapeRel (const Shape & other)
Appends another shape at the end of this one, relative to the last point of this shape.
booleanDifference()
MultiShape Procedural::Shape::booleanDifference (const Shape & other) const
Computes the difference between this shape and another one.
Both shapes must be closed.
Start shapes
Difference of the two shapes
Parameters
other The shape against which the diffenrence is computed
Returns
The difference of two shapes, as a new shape
Exceptions
Ogre::InvalidStateException Current shapes must be closed and has to contain at least 2 points!
Ogre::InvalidParametersException Other shapes must be closed and has to contain at least 2 points!
booleanIntersect()
MultiShape Procedural::Shape::booleanIntersect (const Shape & other) const
Computes the intersection between this shape and another one.
Both shapes must be closed.
Start shapes
Intersection of the two shapes
Parameters
other The shape against which the intersection is computed
Returns
The intersection of two shapes, as a new shape
Exceptions
Ogre::InvalidStateException Current shapes must be closed and has to contain at least 2 points!
Ogre::InvalidParametersException Other shapes must be closed and has to contain at least 2 points!
booleanUnion()
MultiShape Procedural::Shape::booleanUnion (const Shape & other) const
Computes the union between this shape and another one.
Both shapes must be closed.
Start shapes
Union of the two shapes
Parameters
other The shape against which the union is computed
Returns
The union of two shapes, as a new shape
Exceptions
Ogre::InvalidStateException Current shapes must be closed and has to contain at least 2 points!
Ogre::InvalidParametersException Other shapes must be closed and has to contain at least 2 points!
close()
Shape& Procedural::Shape::close ()
Makes the shape a closed shape, ie it will automatically connect the last point to the first point.
Referenced by extractSubShape(), Procedural::RectangleShape::realizeShape(), Procedural::CircleShape::realizeShape(), Procedural::EllipseShape::realizeShape(), and Procedural::TriangleShape::realizeShape().
convertToPath()
Path Procedural::Shape::convertToPath () const
Converts the shape to a path, with Y=0.
convertToTrack()
Track Procedural::Shape::convertToTrack (Track::AddressingMode addressingMode = Track::AM_RELATIVE_LINEIC) const
Outputs a track, with Key=X and Value=Y.
extractSubShape()
Shape Procedural::Shape::extractSubShape (unsigned int first, unsigned int last)
Extracts a part of the shape as a new shape.
Parameters
first first index to be in the new shape
last last index to be in the new shape
References addPoint(), close(), and setOutSide().
findBoundingRadius()
Ogre::Real Procedural::Shape::findBoundingRadius () const
Computes the radius of a bounding circle centered on the origin.
References Ogre::Math::Sqrt().
findRealOutSide()
Side Procedural::Shape::findRealOutSide () const
On a closed shape, find if the outside is located on the right or on the left.
If the outside can easily be guessed in your context, you'd rather use setOutside(), which doesn't need any computation.
getAvgDirection()
Ogre::Vector2 Procedural::Shape::getAvgDirection (unsigned int i) const
Gets the average between before direction and after direction.
References Vector< 2, Real >::normalisedCopy().
getAvgNormal()
Ogre::Vector2 Procedural::Shape::getAvgNormal (unsigned int i) const
Gets the "normal" of that point ie an average between before and after normals.
References Procedural::SIDE_RIGHT.
getBoundedIndex()
unsigned int Procedural::Shape::getBoundedIndex (int i) const
References Procedural::Utils::cap(), and Procedural::Utils::modulo().
getDirectionAfter()
Ogre::Vector2 Procedural::Shape::getDirectionAfter (unsigned int i) const
Returns local direction after the current point.
References Vector< 2, Real >::normalisedCopy().
getDirectionBefore()
Ogre::Vector2 Procedural::Shape::getDirectionBefore (unsigned int i) const
Returns local direction after the current point.
References Vector< 2, Real >::normalisedCopy().
getNormalAfter()
Ogre::Vector2 Procedural::Shape::getNormalAfter (unsigned int i) const
Gets the shape normal just after that point.
References Procedural::SIDE_RIGHT.
getNormalBefore()
Ogre::Vector2 Procedural::Shape::getNormalBefore (unsigned int i) const
Gets the shape normal just before that point.
References Procedural::SIDE_RIGHT.
getOutSide()
Side Procedural::Shape::getOutSide () const
Gets which side is out.
getPoint()
const Ogre::Vector2& Procedural::Shape::getPoint (int i) const
Bounds-safe method to get a point : it will allow you to go beyond the bounds.
getPointCount()
const std::vector<Ogre::Vector2>::size_type Procedural::Shape::getPointCount () const
Gets number of points in current point list.
getPoints()
std::vector<Ogre::Vector2> Procedural::Shape::getPoints () const
Gets a copy of raw vector data of this shape.
getPointsReference() [1/2]
std::vector<Ogre::Vector2>& Procedural::Shape::getPointsReference ()
Gets raw vector data of this shape as a non-const reference.
getPointsReference() [2/2]
const std::vector<Ogre::Vector2>& Procedural::Shape::getPointsReference () const
Gets raw vector data of this shape as a non-const reference.
getPosition() [1/2]
Ogre::Vector2 Procedural::Shape::getPosition (Ogre::Real coord) const
Gets a position on the shape from lineic coordinate.
Parameters
coord lineic coordinate
Exceptions
Ogre::InvalidStateException The shape must at least contain 2 points
References Ogre::Exception::ERR_INVALID_STATE, getPosition(), and OGRE_EXCEPT.
getPosition() [2/2]
Ogre::Vector2 Procedural::Shape::getPosition (unsigned int i, Ogre::Real coord) const
Gets a position on the shape with index of the point and a percentage of position on the segment.
Parameters
i index of the segment
coord a number between 0 and 1 meaning the percentage of position on the segment
Exceptions
Ogre::InvalidParametersException i is out of bounds
Ogre::InvalidParametersException coord must be comprised between 0 and 1
References Ogre::Exception::ERR_INVALIDPARAMS, and OGRE_EXCEPT.
getSegCount()
size_t Procedural::Shape::getSegCount () const
Gets the number of segments in that shape.
getTotalLength()
Ogre::Real Procedural::Shape::getTotalLength () const
Returns the total lineic length of that shape.
insertPoint() [1/2]
Shape& Procedural::Shape::insertPoint (size_t index, const Ogre::Vector2 & pt)
Inserts a point to the shape.
Parameters
index the index before the inserted point
pt new point's position
insertPoint() [2/2]
Shape& Procedural::Shape::insertPoint (size_t index, Ogre::Real x, Ogre::Real y)
Inserts a point to the shape.
Parameters
index the index before the inserted point
x new point's x coordinate
y new point's y coordinate
isClosed()
bool Procedural::Shape::isClosed () const
Gets whether the shape is closed or not.
isOutsideRealOutside()
bool Procedural::Shape::isOutsideRealOutside () const
Determines whether the outside as defined by user equals "real" outside.
isPointInside()
bool Procedural::Shape::isPointInside (const Ogre::Vector2 & point) const
Tells whether a point is inside a shape or not.
Parameters
point The point to check
Returns
true if the point is inside this shape, false otherwise
mergeKeysWithTrack()
Shape Procedural::Shape::mergeKeysWithTrack (const Track & track) const
Creates a shape with the keys of this shape and extra keys coming from a track.
Parameters
track the track to merge keys with
Returns
a new Shape coming from the merge between original shape and the track
mirror() [1/2]
Shape& Procedural::Shape::mirror (bool flip = false)
Create a symetric copy at the origin point.
Parameters
flip true if function should start mirroring with the last point in list (default false)
mirror() [2/2]
Shape& Procedural::Shape::mirror (Ogre::Real x, Ogre::Real y, bool flip = false)
Create a symetric copy at a given point.
Parameters
x x coordinate of point where to mirror
y y coordinate of point where to mirror
flip true if function should start mirroring with the last point in list (default false)
mirrorAroundAxis()
Shape& Procedural::Shape::mirrorAroundAxis (const Ogre::Vector2 & axis, bool flip = false)
Create a symetric copy at a given axis.
Parameters
axis Axis where to mirror
flip true if function should start mirroring with the first point in list (default false)
References Vector< 2, Real >::normalisedCopy(), and Vector< 2, Real >::reflect().
mirrorAroundPoint()
Shape& Procedural::Shape::mirrorAroundPoint (Ogre::Vector2 point, bool flip = false)
Create a symetric copy at a given point.
Parameters
point Point where to mirror
flip true if function should start mirroring with the last point in list (default false)
realizeMesh()
Ogre::MeshPtr Procedural::Shape::realizeMesh (const std::string & name = "") const
Outputs a mesh representing the shape.
Mostly for debugging purposes
reflect()
Shape& Procedural::Shape::reflect (const Ogre::Vector2 & normal)
Reflect all points in this shape against a zero-origined line with a given normal.
Parameters
normal the normal
References reflect().
Referenced by reflect().
reset()
Shape& Procedural::Shape::reset ()
Clears the content of the shape.
reverse()
Shape& Procedural::Shape::reverse ()
Reverses direction of the shape The outside is preserved.
rotate()
Shape& Procedural::Shape::rotate (Ogre::Radian angle)
Applies the given rotation to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
angle angle of rotation
References Ogre::Math::Cos(), Ogre::Math::Sin(), and Ogre::Radian::valueRadians().
scale() [1/3]
Shape& Procedural::Shape::scale (const Ogre::Vector2 & amount)
Applies the given scale to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
amount of scale
scale() [2/3]
Shape& Procedural::Shape::scale (Ogre::Real amount)
Applies the given scale to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
amount amount of scale
scale() [3/3]
Shape& Procedural::Shape::scale (Ogre::Real scaleX, Ogre::Real scaleY)
Applies the given scale to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
scaleX amount of scale in the X direction
scaleY amount of scale in the Y direction
setOutSide()
Shape& Procedural::Shape::setOutSide (Side side)
Sets which side (left or right) is on the outside of the shape.
It is used for such things as normal generation Default is right, which corresponds to placing points anti-clockwise.
Referenced by extractSubShape().
switchSide()
Shape& Procedural::Shape::switchSide ()
Switches the inside and the outside.
References Procedural::SIDE_LEFT, and Procedural::SIDE_RIGHT.
thicken()
MultiShape Procedural::Shape::thicken (Ogre::Real amount)
Applies a "thickness" to a shape, ie a bit like the extruder, but in 2D.
Start shape (before thicken)
Result (after thicken)
translate() [1/2]
Shape& Procedural::Shape::translate (const Ogre::Vector2 & translation)
Applies the given translation to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
translation the translation vector
Referenced by Procedural::TriangleShape::realizeShape().
translate() [2/2]
Shape& Procedural::Shape::translate (Ogre::Real translationX, Ogre::Real translationY)
Applies the given translation to all the points already defined.
Has strictly no effect on the points defined after that
Parameters
translationX X component of the translation vector
translationY Y component of the translation vector
References translate().
The documentation for this class was generated from the following file:
ProceduralShape.h