Ogre Procedural: Procedural::TextureBuffer Class Reference
Procedural::TextureBuffer Class Reference
class to store image data while processing
#include <ProceduralTextureBuffer.h>
Public Member Functions
void setPixel (size_t x, size_t y, Ogre::ColourValue colour)
Set colour of a specified pixel.
void setPixel (size_t x, size_t y, Ogre::uchar red, Ogre::uchar green, Ogre::uchar blue, Ogre::uchar alpha=255)
Set colour of a specified pixel.
void setPixel (size_t x, size_t y, Ogre::Real red, Ogre::Real green, Ogre::Real blue, Ogre::Real alpha=1.0f)
Set colour of a specified pixel.
void setRed (size_t x, size_t y, Ogre::uchar red)
Set red colour value of a specified pixel.
void setGreen (size_t x, size_t y, Ogre::uchar green)
Set green colour value of a specified pixel.
void setBlue (size_t x, size_t y, Ogre::uchar blue)
Set blue colour value of a specified pixel.
void setAlpha (size_t x, size_t y, Ogre::uchar alpha)
Set alpha colour value of a specified pixel.
void setRed (size_t x, size_t y, Ogre::Real red)
Set red colour value of a specified pixel.
void setGreen (size_t x, size_t y, Ogre::Real green)
Set green colour value of a specified pixel.
void setBlue (size_t x, size_t y, Ogre::Real blue)
Set blue colour value of a specified pixel.
void setAlpha (size_t x, size_t y, Ogre::Real alpha)
Set alpha colour value of a specified pixel.
void setData (size_t width, size_t height, Ogre::uchar *data)
Copy image data (RGBA) from a buffer to this object.
void setData (TextureBufferPtr buffer)
Copy image data (RGBA) from an other TextureBuffer object.
Ogre::ColourValue getPixel (size_t x, size_t y) const
Get colour value of a specified pixel.
Ogre::uchar getPixelRedByte (size_t x, size_t y) const
Get red colour value of a specified pixel.
Ogre::uchar getPixelGreenByte (size_t x, size_t y) const
Get green colour value of a specified pixel.
Ogre::uchar getPixelBlueByte (size_t x, size_t y) const
Get blue colour value of a specified pixel.
Ogre::uchar getPixelAlphaByte (size_t x, size_t y) const
Get alpha colour value of a specified pixel.
Ogre::Real getPixelRedReal (size_t x, size_t y) const
Get red colour value of a specified pixel.
Ogre::Real getPixelGreenReal (size_t x, size_t y) const
Get green colour value of a specified pixel.
Ogre::Real getPixelBlueReal (size_t x, size_t y) const
Get blue colour value of a specified pixel.
Ogre::Real getPixelAlphaReal (size_t x, size_t y) const
Get alpha colour value of a specified pixel.
TextureBufferPtr clone () const
Create a copy of the current texture image buffer.
TextureBuffer (TextureBufferPtr tocopy)
Standard constructor which copy a given image.
TextureBuffer (Ogre::uint width_height)
Standard constructor which creates a quadratic image buffer with the given size.
~TextureBuffer ()
Destructor which release memory.
Ogre::uint getWidth () const
Get the width of the stored image in px.
Ogre::uint getHeight () const
Get the height of the stored image in px.
Ogre::Image * getImage () const
Create a new image from buffer.
void saveImage (Ogre::String filename) const
Save the image from the buffer to a file.
Ogre::TexturePtr createTexture (Ogre::String name, Ogre::String group=Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME) const
Creates an OGRE texture and add it to current TextureManager instance.
Detailed Description
class to store image data while processing
Create a TextureBuffer object and move it to all classes inherited from TextureProcessing
Todo:
Increase speed of reading and writeing pixel values.
Constructor & Destructor Documentation
TextureBuffer() [1/2]
Procedural::TextureBuffer::TextureBuffer (TextureBufferPtr tocopy)
Standard constructor which copy a given image.
Parameters
tocopy Image which to copy
Exceptions
Ogre::InvalidParametersException Pointer to source image must not be NULL!
TextureBuffer() [2/2]
Procedural::TextureBuffer::TextureBuffer (Ogre::uint width_height)
Standard constructor which creates a quadratic image buffer with the given size.
Parameters
width_height Edge length in px
Exceptions
Ogre::InvalidParametersException Minimum edge size is 8!
~TextureBuffer()
Procedural::TextureBuffer::~TextureBuffer ()
Destructor which release memory.
Member Function Documentation
clone()
TextureBufferPtr Procedural::TextureBuffer::clone () const
Create a copy of the current texture image buffer.
Note
You have to delete cloned object by yourself!
createTexture()
Ogre::TexturePtr Procedural::TextureBuffer::createTexture (Ogre::String name, Ogre::String group = Ogre::ResourceGroupManager::DEFAULT_RESOURCE_GROUP_NAME) const
Creates an OGRE texture and add it to current TextureManager instance.
Parameters
name Name of the texture
group Name of the resource group where to list the texture
getHeight()
Ogre::uint Procedural::TextureBuffer::getHeight () const
Get the height of the stored image in px.
Referenced by Procedural::Blit::Blit(), Procedural::CircleTexture::CircleTexture(), Procedural::EllipseTexture::EllipseTexture(), Procedural::Polygon::Polygon(), and Procedural::RectangleTexture::RectangleTexture().
getImage()
Ogre::Image* Procedural::TextureBuffer::getImage () const
Create a new image from buffer.
getPixel()
Ogre::ColourValue Procedural::TextureBuffer::getPixel (size_t x, size_t y) const
Get colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return colour value as an Ogre::ColourValue object.
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelAlphaByte()
Ogre::uchar Procedural::TextureBuffer::getPixelAlphaByte (size_t x, size_t y) const
Get alpha colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return alpha colour value as a byte [0, 255].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelAlphaReal()
Ogre::Real Procedural::TextureBuffer::getPixelAlphaReal (size_t x, size_t y) const
Get alpha colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return alpha colour value as a Ogre::Real [0.0, 1.0].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelBlueByte()
Ogre::uchar Procedural::TextureBuffer::getPixelBlueByte (size_t x, size_t y) const
Get blue colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return blue colour value as a byte [0, 255].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelBlueReal()
Ogre::Real Procedural::TextureBuffer::getPixelBlueReal (size_t x, size_t y) const
Get blue colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return blue colour value as a Ogre::Real [0.0, 1.0].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelGreenByte()
Ogre::uchar Procedural::TextureBuffer::getPixelGreenByte (size_t x, size_t y) const
Get green colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return green colour value as a byte [0, 255].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelGreenReal()
Ogre::Real Procedural::TextureBuffer::getPixelGreenReal (size_t x, size_t y) const
Get green colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return green colour value as a Ogre::Real [0.0, 1.0].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelRedByte()
Ogre::uchar Procedural::TextureBuffer::getPixelRedByte (size_t x, size_t y) const
Get red colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return red colour value as a byte [0, 255].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getPixelRedReal()
Ogre::Real Procedural::TextureBuffer::getPixelRedReal (size_t x, size_t y) const
Get red colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
Returns
Return red colour value as a Ogre::Real [0.0, 1.0].
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
getWidth()
Ogre::uint Procedural::TextureBuffer::getWidth () const
Get the width of the stored image in px.
Referenced by Procedural::Blit::Blit(), Procedural::CircleTexture::CircleTexture(), Procedural::EllipseTexture::EllipseTexture(), Procedural::Polygon::Polygon(), and Procedural::RectangleTexture::RectangleTexture().
saveImage()
void Procedural::TextureBuffer::saveImage (Ogre::String filename) const
Save the image from the buffer to a file.
Parameters
filename Name (and path) of the image file where to save the buffer.
setAlpha() [1/2]
void Procedural::TextureBuffer::setAlpha (size_t x, size_t y, Ogre::Real alpha)
Set alpha colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
alpha New alpha value of pixel colour [0.0, 1.0]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setAlpha() [2/2]
void Procedural::TextureBuffer::setAlpha (size_t x, size_t y, Ogre::uchar alpha)
Set alpha colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
alpha New alpha value of pixel colour [0, 255]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setBlue() [1/2]
void Procedural::TextureBuffer::setBlue (size_t x, size_t y, Ogre::Real blue)
Set blue colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
blue New blue value of pixel colour [0.0, 1.0]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setBlue() [2/2]
void Procedural::TextureBuffer::setBlue (size_t x, size_t y, Ogre::uchar blue)
Set blue colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
blue New blue value of pixel colour [0, 255]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setData() [1/2]
void Procedural::TextureBuffer::setData (size_t width, size_t height, Ogre::uchar * data)
Copy image data (RGBA) from a buffer to this object.
Parameters
width Width of the image in buffer
height Height of the image in buffer
data Image buffer as source for copy
setData() [2/2]
void Procedural::TextureBuffer::setData (TextureBufferPtr buffer)
Copy image data (RGBA) from an other TextureBuffer object.
Parameters
buffer Image buffer as source for copy
setGreen() [1/2]
void Procedural::TextureBuffer::setGreen (size_t x, size_t y, Ogre::Real green)
Set green colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
green New green value of pixel colour [0.0, 1.0]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setGreen() [2/2]
void Procedural::TextureBuffer::setGreen (size_t x, size_t y, Ogre::uchar green)
Set green colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
green New green value of pixel colour [0, 255]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setPixel() [1/3]
void Procedural::TextureBuffer::setPixel (size_t x, size_t y, Ogre::ColourValue colour)
Set colour of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
colour New colour of pixel
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
References Ogre::ColourValue::a, Ogre::ColourValue::b, Ogre::ColourValue::g, and Ogre::ColourValue::r.
setPixel() [2/3]
void Procedural::TextureBuffer::setPixel (size_t x, size_t y, Ogre::Real red, Ogre::Real green, Ogre::Real blue, Ogre::Real alpha = 1.0f)
Set colour of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
red New red value of pixel colour
green New green value of pixel colour [0.0, 1.0]
blue New blue value of pixel colour [0.0, 1.0]
alpha New alpha value of pixel colour [0.0, 1.0]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
Ogre::InvalidParametersException Colour value must be between 0 and 1!
setPixel() [3/3]
void Procedural::TextureBuffer::setPixel (size_t x, size_t y, Ogre::uchar red, Ogre::uchar green, Ogre::uchar blue, Ogre::uchar alpha = 255)
Set colour of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
red New red value of pixel colour [0, 255]
green New green value of pixel colour [0, 255]
blue New blue value of pixel colour [0, 255]
alpha New alpha value of pixel colour [0, 255]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
setRed() [1/2]
void Procedural::TextureBuffer::setRed (size_t x, size_t y, Ogre::Real red)
Set red colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
red New red value of pixel colour [0.0, 1.0]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
Ogre::InvalidParametersException Colour value must be between 0 and 1!
setRed() [2/2]
void Procedural::TextureBuffer::setRed (size_t x, size_t y, Ogre::uchar red)
Set red colour value of a specified pixel.
Parameters
x X position of pixel to paint on (0 <= x < width)
y Y position of pixel to paint on (0 <= y < height)
red New red value of pixel colour [0, 255]
Exceptions
Ogre::InvalidParametersException Pixel location is out of bounds!
The documentation for this class was generated from the following file:
ProceduralTextureBuffer.h