Ogre Procedural: Procedural::TriangleBuffer Class Reference
Procedural::TriangleBuffer Class Reference
This is ogre-procedural's temporary mesh buffer.
#include <ProceduralTriangleBuffer.h>
Classes
struct Section
struct Vertex
Public Member Functions
TriangleBuffer ()
void append (const TriangleBuffer &other)
Section beginSection (std::string sectionName="")
void endSection (Section &section)
Section getFullSection ()
std::vector< Vertex > & getVertices ()
Gets a modifiable reference to vertices.
const std::vector< Vertex > & getVertices () const
Gets a non-modifiable reference to vertices.
std::vector< int > & getIndices ()
Gets a modifiable reference to vertices.
const std::vector< int > & getIndices () const
Gets a non-modifiable reference to indices.
void rebaseOffset ()
Rebase index offset : call that function before you add a new mesh to the triangle buffer.
Ogre::MeshPtr transformToMesh (const std::string &name, const Ogre::String &group="General") const
Builds an Ogre Mesh from this buffer.
TriangleBuffer & vertex (const Vertex &v)
Adds a new vertex to the buffer.
TriangleBuffer & vertex (const Ogre::Vector3 &position, const Ogre::Vector3 &normal, const Ogre::Vector2 &uv)
Adds a new vertex to the buffer.
TriangleBuffer & position (const Ogre::Vector3 &pos)
Adds a new vertex to the buffer.
TriangleBuffer & position (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Adds a new vertex to the buffer.
TriangleBuffer & normal (const Ogre::Vector3 &normal)
Sets the normal of the current vertex.
TriangleBuffer & textureCoord (float u, float v)
Sets the texture coordinates of the current vertex.
TriangleBuffer & textureCoord (const Ogre::Vector2 &vec)
Sets the texture coordinates of the current vertex.
TriangleBuffer & index (int i)
Adds an index to the index buffer.
TriangleBuffer & triangle (int i1, int i2, int i3)
Adds a triangle to the index buffer.
TriangleBuffer & applyTransform (const Ogre::Matrix4 &matrix)
Applies a matrix to transform all vertices inside the triangle buffer.
TriangleBuffer & translate (const Ogre::Vector3 &amount)
Applies the translation immediately to all the points contained in that triangle buffer.
TriangleBuffer & translate (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Applies the translation immediately to all the points contained in that triangle buffer.
TriangleBuffer & rotate (Ogre::Quaternion quat)
Applies the rotation immediately to all the points contained in that triangle buffer.
TriangleBuffer & scale (const Ogre::Vector3 &scale)
Applies an immediate scale operation to that triangle buffer.
TriangleBuffer & scale (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Applies an immediate scale operation to that triangle buffer.
TriangleBuffer & invertNormals ()
Applies normal inversion on the triangle buffer.
void estimateVertexCount (unsigned int vertexCount)
Gives an estimation of the number of vertices need for this triangle buffer.
void estimateIndexCount (unsigned int indexCount)
Gives an estimation of the number of indices needed for this triangle buffer.
Protected Attributes
std::vector< int > mIndices
std::vector< Vertex > mVertices
int globalOffset
int mEstimatedVertexCount
int mEstimatedIndexCount
Vertex * mCurrentVertex
std::map< std::string, Section > mSections
Detailed Description
This is ogre-procedural's temporary mesh buffer.
It stores all the info needed to build an Ogre Mesh, yet is intented to be more flexible, since there is no link towards hardware.
Constructor & Destructor Documentation
TriangleBuffer()
Procedural::TriangleBuffer::TriangleBuffer ()
Member Function Documentation
append()
void Procedural::TriangleBuffer::append (const TriangleBuffer & other)
References mIndices, and mVertices.
applyTransform()
TriangleBuffer& Procedural::TriangleBuffer::applyTransform (const Ogre::Matrix4 & matrix)
Applies a matrix to transform all vertices inside the triangle buffer.
beginSection()
Section Procedural::TriangleBuffer::beginSection (std::string sectionName = "")
References Procedural::TriangleBuffer::Section::buffer, Procedural::TriangleBuffer::Section::mFirstIndex, Procedural::TriangleBuffer::Section::mFirstVertex, and Procedural::TriangleBuffer::Section::mSectionName.
endSection()
void Procedural::TriangleBuffer::endSection (Section & section)
References Procedural::TriangleBuffer::Section::mLastIndex, Procedural::TriangleBuffer::Section::mLastVertex, and Procedural::TriangleBuffer::Section::mSectionName.
estimateIndexCount()
void Procedural::TriangleBuffer::estimateIndexCount (unsigned int indexCount)
Gives an estimation of the number of indices needed for this triangle buffer.
If this function is called several times, it means an extra indices count, not an absolute measure.
estimateVertexCount()
void Procedural::TriangleBuffer::estimateVertexCount (unsigned int vertexCount)
Gives an estimation of the number of vertices need for this triangle buffer.
If this function is called several times, it means an extra vertices count, not an absolute measure.
getFullSection()
Section Procedural::TriangleBuffer::getFullSection ()
References Procedural::TriangleBuffer::Section::buffer, Procedural::TriangleBuffer::Section::mFirstIndex, Procedural::TriangleBuffer::Section::mFirstVertex, Procedural::TriangleBuffer::Section::mLastIndex, Procedural::TriangleBuffer::Section::mLastVertex, and Procedural::TriangleBuffer::Section::mSectionName.
getIndices() [1/2]
std::vector<int>& Procedural::TriangleBuffer::getIndices ()
Gets a modifiable reference to vertices.
getIndices() [2/2]
const std::vector<int>& Procedural::TriangleBuffer::getIndices () const
Gets a non-modifiable reference to indices.
getVertices() [1/2]
std::vector<Vertex>& Procedural::TriangleBuffer::getVertices ()
Gets a modifiable reference to vertices.
getVertices() [2/2]
const std::vector<Vertex>& Procedural::TriangleBuffer::getVertices () const
Gets a non-modifiable reference to vertices.
index()
TriangleBuffer& Procedural::TriangleBuffer::index (int i)
Adds an index to the index buffer.
Index is relative to the latest rebaseOffset().
invertNormals()
TriangleBuffer& Procedural::TriangleBuffer::invertNormals ()
Applies normal inversion on the triangle buffer.
References std::swap().
normal()
TriangleBuffer& Procedural::TriangleBuffer::normal (const Ogre::Vector3 & normal)
Sets the normal of the current vertex.
References Procedural::TriangleBuffer::Vertex::mNormal.
Referenced by Procedural::MeshGenerator< TorusGenerator >::addPoint().
position() [1/2]
TriangleBuffer& Procedural::TriangleBuffer::position (const Ogre::Vector3 & pos)
Adds a new vertex to the buffer.
References v.
Referenced by Procedural::MeshGenerator< TorusGenerator >::addPoint().
position() [2/2]
TriangleBuffer& Procedural::TriangleBuffer::position (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Adds a new vertex to the buffer.
References v.
rebaseOffset()
void Procedural::TriangleBuffer::rebaseOffset ()
Rebase index offset : call that function before you add a new mesh to the triangle buffer.
rotate()
TriangleBuffer& Procedural::TriangleBuffer::rotate (Ogre::Quaternion quat)
Applies the rotation immediately to all the points contained in that triangle buffer.
Parameters
quat the rotation quaternion to apply
References Ogre::Quaternion::normalise().
scale() [1/2]
TriangleBuffer& Procedural::TriangleBuffer::scale (const Ogre::Vector3 & scale)
Applies an immediate scale operation to that triangle buffer.
Parameters
scale Scale vector
scale() [2/2]
TriangleBuffer& Procedural::TriangleBuffer::scale (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Applies an immediate scale operation to that triangle buffer.
Parameters
x X scale component
y Y scale component
z Z scale component
textureCoord() [1/2]
TriangleBuffer& Procedural::TriangleBuffer::textureCoord (const Ogre::Vector2 & vec)
Sets the texture coordinates of the current vertex.
References Procedural::TriangleBuffer::Vertex::mUV.
textureCoord() [2/2]
TriangleBuffer& Procedural::TriangleBuffer::textureCoord (float u, float v)
Sets the texture coordinates of the current vertex.
References Procedural::TriangleBuffer::Vertex::mUV, u, and v.
Referenced by Procedural::MeshGenerator< TorusGenerator >::addPoint().
transformToMesh()
Ogre::MeshPtr Procedural::TriangleBuffer::transformToMesh (const std::string & name, const Ogre::String & group = "General") const
Builds an Ogre Mesh from this buffer.
Referenced by Procedural::MeshGenerator< TorusGenerator >::realizeMesh().
translate() [1/2]
TriangleBuffer& Procedural::TriangleBuffer::translate (const Ogre::Vector3 & amount)
Applies the translation immediately to all the points contained in that triangle buffer.
Parameters
amount translation vector
translate() [2/2]
TriangleBuffer& Procedural::TriangleBuffer::translate (Ogre::Real x, Ogre::Real y, Ogre::Real z)
Applies the translation immediately to all the points contained in that triangle buffer.
References translate().
triangle()
TriangleBuffer& Procedural::TriangleBuffer::triangle (int i1, int i2, int i3)
Adds a triangle to the index buffer.
Index is relative to the latest rebaseOffset().
vertex() [1/2]
TriangleBuffer& Procedural::TriangleBuffer::vertex (const Ogre::Vector3 & position, const Ogre::Vector3 & normal, const Ogre::Vector2 & uv)
Adds a new vertex to the buffer.
References v.
vertex() [2/2]
TriangleBuffer& Procedural::TriangleBuffer::vertex (const Vertex & v)
Adds a new vertex to the buffer.
References v.
Member Data Documentation
globalOffset
int Procedural::TriangleBuffer::globalOffset protected
mCurrentVertex
Vertex* Procedural::TriangleBuffer::mCurrentVertex protected
mEstimatedIndexCount
int Procedural::TriangleBuffer::mEstimatedIndexCount protected
mEstimatedVertexCount
int Procedural::TriangleBuffer::mEstimatedVertexCount protected
mIndices
std::vector<int> Procedural::TriangleBuffer::mIndices protected
Referenced by append().
mSections
std::map<std::string, Section> Procedural::TriangleBuffer::mSections protected
mVertices
std::vector<Vertex> Procedural::TriangleBuffer::mVertices protected
Referenced by append().
The documentation for this class was generated from the following file:
ProceduralTriangleBuffer.h