Ogre Procedural: Procedural::MultiShape Class Reference
Procedural::MultiShape Class Reference
Shape
#include <ProceduralMultiShape.h>
Public Member Functions
MultiShape ()
Default constructor.
MultiShape (const Shape &shape)
Constructor from a single shape.
MultiShape (int count,...)
Constructor from a variable number of shapes.
MultiShape & addShape (const Shape &shape)
Adds a shape to the list of shapes.
void clear ()
Clears all the content.
const Shape & getShape (unsigned int i) const
Returns the i-th shape.
Shape & getShape (unsigned int i)
Returns the i-th shape.
std::vector< Ogre::Vector2 > getPoints () const
Builds an aggregated list of all points contained in all shapes.
unsigned int getShapeCount () const
Returns the number of shapes in that MultiShape.
void addMultiShape (const MultiShape &other)
Append every shape of an other multishape to the current multiShape.
Ogre::MeshPtr realizeMesh (const std::string &name="")
Outputs the Multi Shape to a Mesh, mostly for visualisation or debugging purposes.
bool isPointInside (const Ogre::Vector2 &point) const
Tells whether a point is located inside that multishape It assumes that all of the shapes in that multishape are closed, and that they don't contradict each other, ie a point cannot be outside and inside at the same time.
bool isClosed () const
Tells whether multishape is "closed" or not.
void close ()
Closes all shapes included in this multiShape.
bool isOutsideRealOutside () const
Determines whether the outside as defined by user equals "real" outside.
void buildFromSegmentSoup (const std::vector< Segment2D > &segList)
Detailed Description
Holds a bunch of shapes. There are a number of assumptions that are made and are not checked against : the shapes must not cross each other
Constructor & Destructor Documentation
MultiShape() [1/3]
Procedural::MultiShape::MultiShape ()
Default constructor.
MultiShape() [2/3]
Procedural::MultiShape::MultiShape (const Shape & shape)
Constructor from a single shape.
MultiShape() [3/3]
Procedural::MultiShape::MultiShape (int count, ...)
Constructor from a variable number of shapes.
Parameters
count the number of shapes to add
... pointer to the shapes to add
Member Function Documentation
addMultiShape()
void Procedural::MultiShape::addMultiShape (const MultiShape & other)
Append every shape of an other multishape to the current multiShape.
Referenced by Procedural::Extruder::setMultiShapeToExtrude().
addShape()
MultiShape& Procedural::MultiShape::addShape (const Shape & shape)
Adds a shape to the list of shapes.
Referenced by Procedural::Extruder::setShapeToExtrude().
buildFromSegmentSoup()
void Procedural::MultiShape::buildFromSegmentSoup (const std::vector< Segment2D > & segList)
clear()
void Procedural::MultiShape::clear ()
Clears all the content.
Referenced by Procedural::Extruder::setMultiShapeToExtrude(), and Procedural::Extruder::setShapeToExtrude().
close()
void Procedural::MultiShape::close ()
Closes all shapes included in this multiShape.
getPoints()
std::vector<Ogre::Vector2> Procedural::MultiShape::getPoints () const
Builds an aggregated list of all points contained in all shapes.
getShape() [1/2]
Shape& Procedural::MultiShape::getShape (unsigned int i)
Returns the i-th shape.
getShape() [2/2]
const Shape& Procedural::MultiShape::getShape (unsigned int i) const
Returns the i-th shape.
getShapeCount()
unsigned int Procedural::MultiShape::getShapeCount () const
Returns the number of shapes in that MultiShape.
isClosed()
bool Procedural::MultiShape::isClosed () const
Tells whether multishape is "closed" or not.
MultiShape is considered to be closed if and only if all shapes are closed
isOutsideRealOutside()
bool Procedural::MultiShape::isOutsideRealOutside () const
Determines whether the outside as defined by user equals "real" outside.
isPointInside()
bool Procedural::MultiShape::isPointInside (const Ogre::Vector2 & point) const
Tells whether a point is located inside that multishape It assumes that all of the shapes in that multishape are closed, and that they don't contradict each other, ie a point cannot be outside and inside at the same time.
realizeMesh()
Ogre::MeshPtr Procedural::MultiShape::realizeMesh (const std::string & name = "")
Outputs the Multi Shape to a Mesh, mostly for visualisation or debugging purposes.
The documentation for this class was generated from the following file:
ProceduralMultiShape.h