Ogre Procedural: Procedural::MultiPath Class Reference
Procedural::MultiPath Class Reference
#include <ProceduralPath.h>
Classes
struct PathCoordinate
Public Types
typedef std::vector< PathCoordinate > PathIntersection
Public Member Functions
void clear ()
MultiPath & addPath (const Path &path)
MultiPath & addMultiPath (const MultiPath &multiPath)
void setPath (unsigned int i, const Path &path)
unsigned int getPathCount () const
Path getPath (unsigned int i) const
void _calcIntersections ()
const std::map< PathCoordinate, PathIntersection > & getIntersectionsMap () const
const std::vector< PathIntersection > & getIntersections () const
std::vector< std::pair< unsigned int, unsigned int > > getNoIntersectionParts (unsigned int pathIndex) const
Member Typedef Documentation
PathIntersection
typedef std::vector<PathCoordinate> Procedural::MultiPath::PathIntersection
Member Function Documentation
_calcIntersections()
void Procedural::MultiPath::_calcIntersections ()
Referenced by Procedural::Extruder::setExtrusionPath().
addMultiPath()
MultiPath& Procedural::MultiPath::addMultiPath (const MultiPath & multiPath)
Referenced by Procedural::Extruder::setExtrusionPath().
addPath()
MultiPath& Procedural::MultiPath::addPath (const Path & path)
Referenced by Procedural::Extruder::setExtrusionPath().
clear()
void Procedural::MultiPath::clear ()
Referenced by Procedural::Extruder::setExtrusionPath().
getIntersections()
const std::vector<PathIntersection>& Procedural::MultiPath::getIntersections () const
getIntersectionsMap()
const std::map<PathCoordinate, PathIntersection>& Procedural::MultiPath::getIntersectionsMap () const
getNoIntersectionParts()
std::vector<std::pair<unsigned int, unsigned int> > Procedural::MultiPath::getNoIntersectionParts (unsigned int pathIndex) const
References Procedural::Path::getSegCount(), and result.
getPath()
Path Procedural::MultiPath::getPath (unsigned int i) const
getPathCount()
unsigned int Procedural::MultiPath::getPathCount () const
setPath()
void Procedural::MultiPath::setPath (unsigned int i, const Path & path)
The documentation for this class was generated from the following file:
ProceduralPath.h