name: CI Build
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libogre-1.12-dev
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cmake -Bbuild .
        cmake --build build -- -j 2
